version: "3.7"
services:
  gateway-envoy:
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "80:80"
      - "8001:8001"

  go-service:
    build:
      context: ./go-service
      dockerfile: ./Dockerfile
    networks:
      envoymesh:
    expose:
      - "81"
    ports:
      - "81:81"

networks:
  envoymesh: {}
