version: "3.7"
services:
  gateway-envoy:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  go-service:
    build:
      context: .
      dockerfile: ./go-service/Dockerfile-service
    networks:
      envoymesh:
    expose:
      - "81"

  # dotnet-service:
  #   build:
  #     context: .
  #     dockerfile: ./dotnet-service/Dockerfile
  #   networks:
  #     envoymesh:
  #   expose:
  #     - "80"

networks:
  envoymesh: {}
