version: "3.7"
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - envoymesh
    expose:
      - "7778"
      - "9901"
    ports:
      - "7778:7778"
      - "9901:9901"

networks:
  envoymesh: {}
